# Features Details
numerical_feature:
 - 'Age'
 - 'DailyRate'
 - 'DistanceFromHome'
 - 'Education'
 - 'EmployeeCount'
 - 'EmployeeNumber'
 - 'EnvironmentSatisfaction'
 - 'HourlyRate'
 - 'JobInvolvement'
 - 'JobLevel'
 - 'JobSatisfaction'
 - 'MonthlyIncome'
 - 'MonthlyRate'
 - 'NumCompaniesWorked'
 - 'PercentSalaryHike'
 - 'PerformanceRating'
 - 'RelationshipSatisfaction'
 - 'StandardHours'
 - 'StockOptionLevel'
 - 'TotalWorkingYears'
 - 'TrainingTimesLastYear'
 - 'WorkLifeBalance'
 - 'YearsAtCompany'
 - 'YearsInCurrentRole'
 - 'YearsSinceLastPromotion'
 - 'YearsWithCurrManager'

categorical_feature:
 - 'BusinessTravel'
 - 'Department'
 - 'EducationField'
 - 'Gender'
 - 'JobRole'
 - 'MaritalStatus'
 - 'Over18'
 - 'OverTime'

target_feature: 'Attrition'

significant_features:
 - 'JobInvolvement'
 - 'JobLevel'
 - 'StockOptionLevel'
 - 'JobRole'
 - 'MaritalStatus'
 - 'OverTime'
 - 'DistanceFromHome'
 - 'HourlyRate'
 - 'MonthlyRate'
 - 'NumCompaniesWorked'
 - 'PercentSalaryHike'
 - 'TrainingTimesLastYear'
 - 'YearsSinceLastPromotion'
 - 'Attrition'

sacle_features:
  - 'HourlyRate'
  - 'MonthlyRate'
  - 'PercentSalaryHike'
  - 'TrainingTimesLastYear'
  - 'YearsSinceLastPromotion'
  - 'JobInvolvement'
  - 'JobLevel'
  - 'StockOptionLevel'
  - 'DistanceFromHome'
  - 'NumCompaniesWorked'

ohe_features:
  - 'OverTime'
  - 'MaritalStatus'
  - 'JobRole'
